# Generated by Django 3.1.2 on 2024-04-25 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201029_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.date(2024, 4, 25)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_placed',
            field=models.TimeField(default=datetime.datetime(2024, 4, 25, 17, 37, 53, 344091)),
        ),
    ]
