# Generated by Django 3.1.2 on 2024-04-25 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20240425_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_placed',
            field=models.TimeField(default=datetime.datetime(2024, 4, 25, 18, 35, 18, 882102)),
        ),
    ]
